name: infinite_listview_bloc
version: 1.0.0
description: >
  Infinite listview
issue_tracker: https://github.com/zoocityboy/infinity_list_bloc/issues
homepage: https://pub.dev/packages/infinity_list_bloc
documentation: https://github.com/zoocityboy/infinity_list_bloc
repository: https://github.com/zoocityboy/infinity_list_bloc

environment:
  sdk: ">3.0.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  equatable: ">=2.0.5 <2.1.0"
  flutter:
    sdk: flutter
  flutter_bloc: ">=8.1.3 <8.2.0"
  flutter_staggered_animations: ">=1.1.0 <2.0.0"
  meta: ">=1.9.0 <2.0.0"
dev_dependencies:
  bloc_test: ">=9.1.3 <9.2.0"
  flutter_test:
    sdk: flutter
  mocktail: ">=0.3.0 <0.4.0"
  test: ^1.21.0
  zoo_lints: ">=3.0.0 <3.1.0"

flutter: null
